apiVersion: apps/v1
kind: Deployment
metadata:
  name: appinsights2070
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai2070
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai2070
    spec:
      containers:
      - image: REPLACE_THIS.azurecr.io/appinsights2070:1.0
        imagePullPolicy: Always
        name: ai
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30